nguage: node_js
node_js:
- stable
install:
- npm install
- bower install
script:
- npm test
notifications:
  slack:
    secure: UCScbRdZiDwVEK0ra6IPmUGujay8ylPI/uqiEXRzxeloIitVjD7DN+R031yKrqqGLCa9jOLpeIcQ+BhDkAiw4kma6KuQIMc/XW4zpTbXoMFwGv3GwqhPSZrjAnMm0CJy1mlgw06x3OO7qjk/k1/SnrxsFtuk9Yq1s7LbVbdellxQt9WG6OJG6kwe31hssklxR0TYNxqvkA7rkfPJD8wEoUeyiG1qASQOC3ptQRW+kFE+kTXY55OwKUPqpQqhva5wA/jyblDM9yN469lwsx9E6fybVCicDEyVI1Jy5l8JfeEvI7LTmvE7o6DVrM3j+T8JK0O/EME7XyIMgP7O1o+iQ3I3NKgb6j8Lo2e0YubuTENYzfhGOora00ovDSvjMdR4D4QSjUfUeaD47ilkQp5lefqsj/0hOSpx3gVls/rirBrMl4yT7Kj9f9KrQwrfwUsN9Xm8gb1+rwxHgwr0mD/1b40VxEBevIE7zYbaMYOTde+sF0kGpkSa21nHACD3h29canTeC/BZ0fg8Fkzt56Xt26LW1jjzvIi6t8C3ZqbfidOV/dwPJQN6qgvGvVbzCqYnAYGcgJ/JBIHJS9yENKopuaf3otUuBWhSD3Ujs8g2547pF+Q5cq5XQMopHXmTxy7TahmFsop1j1rfFSFTg7WFR8tCwOYHlJ49zHKXlbqwwUA=
